version: "3"
services:
  app:
    build:
      context: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "./work:/work" # notebookをホストと共有したいためディレクトリをマウント
    environment:
      - JUPYTER_ENABLE_LAB=yes
        # pass:12345
    command: start.sh jupyter lab --NotebookApp.token=''
